version: '3'

services:
    google_pathways_api:
      image: brighthive/google_pathways_api:latest
      depends_on:
        - postgres_service
      environment:
        - APP_ENV=LOCAL
        - SECRET_KEY=supersecretkey
      ports:
        - "8000:8000"
      volumes:
        - ./google_pathways_api:/google-pathways-api/google_pathways_api
      stdin_open: true
      tty: true
    postgres_service:
      image: postgres:12
      environment:
        - POSTGRES_USER=dt_admin
        - POSTGRES_PASSWORD=passw0rd
        - POSTGRES_DB=pathways_test
      ports:
        - "5432:5432"