version: '3'

services:
    google_pathways_web_app:
      image: brighthive/google_pathways_web_app:latest
      depends_on:
        - postgres_service
      environment:
        - APP_ENV=LOCAL
        - SECRET_KEY=supersecretkey
      ports:
        - "8000:8000"
      volumes:
        - ./google_pathways_web_app:/google-pathways-web-app/google_pathways_web_app
      stdin_open: true
      tty: true
    postgres_service:
      image: postgres:12
      environment:
        - POSTGRES_USER=brighthive_admin
        - POSTGRES_PASSWORD=passw0rd
        - POSTGRES_DB=pathways
      ports:
        - "10031:5432"
